name: Security Scan

on:
  push:
    branches:
      - develop
      - master
      - feature/*
      - epic/*
      - fix/*
  pull_request:
    branches:
      - develop
      - master

jobs:
  sast-scan:
    runs-on: ubuntu-latest
    
    steps:

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCE_SA_KEY }}
          project_id: ${{ secrets.GCE_PROJECT }}

      - run: |-
          gcloud --quiet auth configure-docker
          docker run --publish 18200:8200 --detach gcr.io/$GCE_PROJECT/sast-engine:dev 
        env:
          GCE_PROJECT: ${{ secrets.GCE_PROJECT }}

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}

      - name: Perform SAST Scan
        run: 'echo "{\"sourcesArchiveBase64\":\"$(zip -q -r - . | base64)\"}" | curl -X POST -H "Content-Type: application/json" -d @- http://localhost:18200/api/analyse -o results.sarif'

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
